### ISSUE TITLE
Template Error

### ISSUE THREAD

**Issue by MrMyatNoe** [AbdullahDev0/nestjs-langchain#4]
[Post](https://medium.com/@abdullahirfan99_80517/langchain-with-nestjs-node-framework-basic-chat-setup-3296fb91ced0)

 I tried steps from your post from medium, but I got this one, could u show me the way how to solve it? 

![langchain](https://github.com/AbdullahDev0/nestjs-langchain/assets/33978217/e5da98c2-5084-46e7-8ee4-bd27cb9582d1)

**Comment by AbdullahDev0** [comment]
Hi @MrMyatNoe, this seems like the prompt variable itself being returned, and not an error, kindly share the code snippet so I can help you further!

**Comment by MrMyatNoe** [comment]
this is my github [repo](https://github.com/MrMyatNoe/langchain-nest.git)

**Comment by AbdullahDev0** [comment]
@MrMyatNoe earlier I missed to mention on how to add OpenAI API key, I have updated that in the article as well. Create a .env file, add OPENAI_API_KEY variable and key from OpenAI here. Hopefully this should resolve the issue!

**Comment by MrMyatNoe** [comment]
@AbdullahDev0  hello, still got the error again even though I added OPENAI_API_KEY = {my_API_key} in .env file,

**Comment by AbdullahDev0** [comment]
@MrMyatNoe  I cloned and ran your code, and found no errors in it. Just to clarify, you defined key as OPENAI_API_KEY={api_key} and not as OPENAI_API_KEY = {my_API_key}? Because in .env there shouldn't be any space.
![image](https://github.com/AbdullahDev0/nestjs-langchain/assets/105665222/d26fca94-9d21-4f02-8aea-d7c67e8872eb)
![image](https://github.com/AbdullahDev0/nestjs-langchain/assets/105665222/cd949a70-c4a8-45a6-9aa6-33c03e03a9a1)

**Comment by MrMyatNoe** [comment]
I ran directly from service layer like this , but still got the same error
<img width="569" alt="Screenshot 2024-04-04 223510" src="https://github.com/AbdullahDev0/nestjs-langchain/assets/33978217/d00d32d4-7e46-4455-9188-86c12946f4ef">







and then I found it out this one, not sure because of this one
<img width="1079" alt="usage" src="https://github.com/AbdullahDev0/nestjs-langchain/assets/33978217/d284b92d-0a47-49de-8e39-b78025626120">

**Comment by AbdullahDev0** [comment]
Yeah, that's the reason. Unfortunately your free credits have expired, so you need to add some balance to use the API
